server:
  port: 8081

spring:
  application:
    name: finance_app

  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

token:
  signing:
    key: ${SING_IN_KEY}
